module.exports = [
  "Things that make you go 'hmm...'",
  "Things you whisper in the dark",
  "Things found in a wizard's pocket",
  "Things you regret buying",
  "Things that are surprisingly heavy",
  "Things you shouldn't Google at work",
  "Things that rhyme with 'orange'",
  "Things superheroes do on their day off",
  "Things you find in a mad scientist's lab",
  "Things that are overrated",
  "Things you yell from a mountaintop",
  "Things that are underrated",
  "Things you shouldn't say to a time traveler",
  "Things that happen in slow motion",
  "Things you keep hidden from your friends",
  "Things that are impossible to lick",
  "Things you do when no one's watching",
  "Things that are better in theory than practice",
  "Things you wish you could unsee",
  "Things that are secretly alive",
  "The worst theme for a wedding",
  "What you don't want to hear from your pilot",
  "A terrible name for a pet rock",
  "The title of your autobiography",
  "What aliens really think of humans",
  "A rejected crayon color",
  "The worst flavor of ice cream imaginable",
  "What dogs actually dream about",
  "A useless superpower to have",
  "The secret ingredient in grandma's cookies",
  "What you'd say to a ghost in your room",
  "The worst time to sneeze loudly",
  "A strange thing to find in your shoe",
  "What the President keeps in their pocket",
  "A bad excuse for being late to a party",
  "Things you shouldn't do while sleepwalking",
  "The worst gift to give on a first date",
  "What cats are actually plotting",
  "A new law you would make if you were King/Queen",
  "The real reason the dinosaurs went extinct",
  "What you would do if you were invisible for a day",
  "A weird thing to collect",
  "What you shouldn't say to a police officer",
  "The worst place to lose your phone",
  "Things that smell better than they taste",
  "The name of a band made up of elderly people",
  "What you find at the end of a rainbow (wrong answers only)",
  "A sign you shouldn't read while driving",
  "Things you shouldn't bring to a job interview",
  "The worst topping for a pizza"
];