module.exports = [
  "Things that make you go 'hmm...'",
  "Things you whisper in the dark",
  "Things found in a wizard's pocket",
  "Things you regret buying",
  "Things that are surprisingly heavy",
  "Things you shouldn't Google at work",
  "Things that rhyme with 'orange'",
  "Things superheroes do on their day off",
  "Things you find in a mad scientist's lab",
  "Things that are overrated",
  "Things you yell from a mountaintop",
  "Things that are underrated",
  "Things you keep hidden from your friends",
  "Things that are better in theory than practice",
  "Things you wish you could unsee",
  "The worst theme for a wedding",
  "What you don't want to hear from your pilot",
  "A terrible name for a pet",
  "The title of your autobiography",
  "What aliens really think of humans",
  "A rejected crayon color",
  "The worst flavor of ice cream imaginable",
  "What dogs actually dream about",
  "A useless superpower to have",
  "The secret ingredient in grandma's cookies",
  "What you'd say to a ghost in your room",
  "The worst time to sneeze loudly",
  "What the President keeps in their pocket",
  "A bad excuse for being late to a party",
  "Things you shouldn't do while sleepwalking",
  "What cats are actually plotting",
  "A new law you would make if you were King/Queen",
  "The real reason the dinosaurs went extinct",
  "What you would do if you were invisible for a day",
  "A weird thing to collect",
  "What you shouldn't say to a police officer",
  "The worst place to lose your phone",
  "Things that smell better than they taste",
  "The name of a band made up of elderly people",
  "What you find at the end of a rainbow (wrong answers only)",
  "Things you shouldn't bring to a job interview",
  "The worst topping for a pizza",
  "Things you can't resist buying",
  "Things that are your kryptonite",
  "Things you shouldn't put in the microwave",
  "Things that are harder than they look",
  "Things you shouldn't juggle",
  "Things you shouldn't write on a Valentine's Day card",
  "Things you wish grew on trees",
  "A bad slogan for a hospital",
  "The worst thing to hear while swimming in the ocean",
  "A sign that you are turning into your parents",
  "The worst possible gift to receive for Christmas",
  "A rejected title for a Disney movie",
  "What the Tooth Fairy actually does with the teeth",
  "The warning label that should come stuck to your forehead",
  "A secret habit you have when no one is looking",
  "The worst thing to say when you meet your in-laws",
  "A terrible theme for a child's birthday party",
  "Things you shouldn't put in a piñata",
  "Things you shouldn't high-five someone for",
  "Things you shouldn't attempt to DIY",
  "What you would buy first if you won the lottery"
];